# -*- coding: utf-8 -*-
"""face2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NS7C2oC-aUzuurbNuYu-7gs19YDC0o81
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import os

#CẤU HÌNH ĐƯỜNG DẪN VÀ THAM SỐ
data_dir = '/content/drive/MyDrive/DATA Emoji RA0001'

IMG_WIDTH, IMG_HEIGHT = 200, 200
BATCH_SIZE = 64

datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,       # Xoay nhẹ 15 độ
    width_shift_range=0.1,   # Dịch ngang nhẹ
    height_shift_range=0.1,  # Dịch dọc nhẹ
    zoom_range=0.15,         # Zoom cận mặt
    horizontal_flip=True,    # Lật gương (rất quan trọng với khuôn mặt)
    validation_split=0.2     # 20% để test
)

train_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

NUM_CLASSES = len(train_generator.class_indices)
print(f"\n👥 Số lượng người cần nhận diện: {NUM_CLASSES}")
print(f"📌 Danh sách: {train_generator.class_indices}")

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(IMG_HEIGHT, IMG_WIDTH, 3))
base_model.trainable = False # Đóng băng lớp gốc

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(NUM_CLASSES, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#BẮT ĐẦU HUẤN LUYỆN
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

checkpoint = ModelCheckpoint('/content/best_face_model.h5', monitor='val_accuracy', save_best_only=True)

EPOCHS = 50

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=EPOCHS,
    callbacks=[early_stop, checkpoint]
)
print("✅ ĐÃ TRAIN XONG VÀ LƯU MÔ HÌNH TẠI /content/best_face_model.h5")

!pip install pillow-heif -q

import ipywidgets as widgets
from IPython.display import display, clear_output
import io
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from PIL import Image
import pillow_heif
import matplotlib.pyplot as plt

# Kích hoạt bộ đọc HEIC
pillow_heif.register_heif_opener()

print("⏳ Đang khởi động AI, vui lòng đợi vài giây...")

try:
    # Load mô hình đã được tải lên Colab (Lưu ý: phải upload file này lên trước khi chạy)
    model = load_model('/content/best_face_model.h5')
except Exception as e:
    print(" KHÔNG TÌM THẤY MÔ HÌNH!")
    raise e

labels = {
    0: 'Hà Nguyễn Minh Anh_31251022430',
    1: 'Hoàng Đình Nguyên_31251027872',
    2: 'Huỳnh Ngọc Vương_31251021464',
    3: 'Huỳnh Nguyễn Phát Sơn_31251021998',
    4: 'Huỳnh Tuyên Chương_31251021888',
    5: 'Lê Duy Nhật_31251025698',
    6: 'Lê Ngọc Bảo Trâm_31251025307',
    7: 'Lê Nguyễn Anh Khoa_31251025754',
    8: 'Lý Tuấn Đạt_31251021889',
    9: 'Ngô Quân Hạo_31251024029',
    10: 'Nguyễn Anh Đức_31251028367',
    11: 'Nguyễn Châu Nguyệt Mẫn_31251025080',
    12: 'Nguyễn Duy Quang_31251020812',
    13: 'Nguyễn Huy Khanh_31251020227',
    14: 'Nguyễn Nam Hồng Phúc_31251020111',
    15: 'Nguyễn Tấn Khang_31251026880',
    16: 'Nguyễn Thị Minh Thư - 31251022343',
    17: 'Nguyễn Thị Minh Thư_31251022940',
    18: 'Nguyễn Trung Thủy Trúc_31251021890',
    19: 'Nguyễn Đăng Hải Đăng - 31241023855',
    20: 'Nguyễn Đức Trung_31251021463',
    21: 'Ninh Công Uy_31251025315',
    22: 'Nông Đình Gia Phong_31251025849',
    23: 'Phạm Hoàng Thái_31251021462',
    24: 'Phạm Xuân Đăng_31251025847',
    25: 'Trần Khắc Triệu_31251022531',
    26: 'Trần Minh Mẫn_31251025599',
    27: 'Trần Thiên Hạo_31251022601',
    28: 'Trần Tiến Đạt_31251022119',
    29: 'Trần Vĩ Khang_31251024909',
    30: 'Võ Lê Gia Huy_31241023619',
    31: 'Võ Lý Thanh Nhã_31251023642',
    32: 'Đặng Hiếu Thiên_312410125173',
    33: 'Đặng Nhật duy Thái_31251025729',
    34: 'Đặng Quốc Vĩnh_31251024120',
    35: 'Đặng Thế Vũ _ 31251025972',
    36: 'Đoàn Thị Quỳnh Như_31251026015',
    37: 'Đỗ Dương Quang_31251021297',
    38: 'Đỗ Minh Nam_31251027063'
}

# Giao diện nút upload ảnh
uploader = widgets.FileUpload(
    accept='image/*',
    multiple=False,
    description='Quét khuôn mặt',
    button_style='success'
)
out = widgets.Output()

def on_upload(change):
    with out:
        clear_output()
        if not uploader.value:
            return

        # Xử lý lấy file từ nút upload (Tương thích nhiều phiên bản Colab)
        try:
            file_info = uploader.value[0]
            content = file_info.content
            name = file_info.name
        except (KeyError, TypeError):
            name = list(uploader.value.keys())[0]
            content = uploader.value[name]['content']

        print(f"⏳ Đang phân tích ảnh: {name}...\n")

        try:
            # Đọc ảnh trực tiếp từ bộ nhớ
            img = Image.open(io.BytesIO(content))
            img = img.convert('RGB')

            # Hiển thị ảnh ra màn hình
            plt.figure(figsize=(4, 4))
            plt.imshow(img)
            plt.axis('off')
            plt.show()


            img_resized = img.resize((200, 200))
            img_array = tf.keras.preprocessing.image.img_to_array(img_resized)
            img_array = np.expand_dims(img_array, axis=0)
            img_array /= 255.0

            # AI tiến hành dự đoán
            predictions = model.predict(img_array, verbose=0)
            predicted_class = np.argmax(predictions[0])
            confidence = np.max(predictions[0]) * 100

            # In kết quả
            print(f"👤 Kết quả nhận diện: {labels.get(predicted_class, 'Không có trong dữ liệu')}")
            print(f"🎯 Độ tự tin: {confidence:.2f}%\n" + "="*40)

        except Exception as e:
            print(f"❌ Có lỗi xảy ra khi đọc bức ảnh này: {e}")

uploader.observe(on_upload, names='value')

print("✅ Đã tải xong AI! Sẵn sàng nhận diện.")
print("=== 📸 HỆ THỐNG DỰ ĐOÁN KHUÔN MẶT 📸 ===")
display(uploader, out)